### ISSUE TITLE
[Request] image url

### ISSUE THREAD

**Issue by AlexVialaBellander** [dcronqvist/systembolaget-api#1]
Hi!

Would it be possible to add image URLs supplied by Systembolaget for each product entry?

**Comment by dcronqvist** [comment]
Good suggestion!

The API I use to pull the data returns an array of image urls, which almost always contains only 1 item, all other times it is empty. I have not seen any example of it returning more than one url.

Do you have any preference on what we do?

1. We make the API return `null` if the url array is empty or the first url in the array if there exists one.
2. We make the API return the same array containing all urls (with the possibility of it being empty) on the off chance that there might be more than one, allowing the consumer of the API to do as they please with all urls instead of restricting them to a single one.

Personally, I am more inclined to implement 2.
